### PR TITLE
feat: django 3.2 and Python 3.9 compatibility 

### PR DESCRIPTION
**Pull request by Aiky30**
* Upgraded the test matrix to use python 3.7, 3.8 and 3.9, with django 2.2 and 3.2

* moved from django.conf.urls.url() to django.urls.re_path()

* replace ugettext with gettext, and ugettext_lazy with gettext_lazy

### CODE REVIEW

**Comment by marksweb** [comment]
I'm using this PR branch to setup cms 4 on a project and raised #78 to share an issue with the migrations.

Perhaps you could include a fix as part of this compatibility work @Aiky30?

I've had to put an early return in migration 8 to resolve;

```
def forwards(apps, schema_editor):
    djangocms_versioning_config_enabled = UrlCMSAppConfig.djangocms_versioning_enabled
    ContentType = apps.get_model("contenttypes", "ContentType")
    Url = apps.get_model("djangocms_url_manager", "Url")
    UrlGrouper = apps.get_model("djangocms_url_manager", "UrlGrouper")
    User = apps.get_model('auth', 'User')

    try:
        url_contenttype = ContentType.objects.get(app_label='djangocms_url_manager', model='url')
        url_queryset = Url.objects.all()
    except ContentType.DoesNotExist:
        return
```

**Comment by Aiky30** [comment]
Ah yes, I see what's happening, this branch needs bringing back up to date with this change: https://github.com/django-cms/djangocms-url-manager/commit/e5e83c686d9aae0673ce66591f383ec94bef536a

**Comment by Aiky30** [comment]
I'm knackered today, will try and find time to pull this in ASAP. @marksweb Is this blocking anything your doing or can it wait until Monday?

**Comment by marksweb** [comment]
@Aiky30 I'm in a similar state today! No rush at all. I've just modified the app to get it running. Doesn't even need to he early next week. I've got plenty to be setting up here for cms & other jobs will get in the way of that next week I bet 😂

My blocker right now is the admin loading js before the dom is ready and I'm not getting select2.

**Comment by Aiky30** [comment]
@marksweb This change will automatically get the fix as that is now merged. Brought this up to date and this is now ready to be reviewed and if approved merged.

**Review by Bernardvdv — CHANGES_REQUESTED** [review]
Changes looks good! 

Requires a changelog entry

**Comment by Aiky30** [comment]
> Changes looks good!
> 
> Requires a changelog entry

Well spotted. Added entry.

**Review by marksweb — APPROVED** [review]
This now migrates on a project without cms 👍

**Review by Bernardvdv — APPROVED** [review]

**Pull request merged**
