### PR TITLE
add support for django 4.2 and python 3.10, drop support for django 2…

### PR DESCRIPTION
**Pull request by FreemanPancake**
* Add support for Django 4.2, now supports Django [3.2, 4.2]
* Add support for Python 3.10, now supports Python [3.8, 3.9, 3.10]
* Drop support for Django 2.x
* Drop support for Python 3.6 & 3.7

### CODE REVIEW

**Comment by joshyu** [comment]
@Aiky30  please help to review. 
I find that the workflow need maintainer's approval and then can run.

**Comment by fsbraun** [comment]
@FreemanPancake @joshyu Can you please reopen this PR against `master`? djangocms-url-manager is fully compatible with django CMS 4.0. The difference of the master branch is, that django 2.2 support already had been removed. We can keep one code base.

**Comment by joshyu** [comment]
> @FreemanPancake @joshyu Can you please reopen this PR against `master`? djangocms-url-manager is fully compatible with django CMS 4.0. The difference of the master branch is, that django 2.2 support already had been removed. We can keep one code base.

Thanks for your confirmation about our work. That makes sense, we will raise another PR based on `master` branch.

**Comment by fsbraun** [comment]
Superseeded by #87

**Pull request closed without merging**
